# Generated by Django 3.1.4 on 2020-12-12 13:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('short_description', models.TextField(blank=True, max_length=240, null=True, verbose_name='Kurze Beschreibung')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('startdate', models.DateField(verbose_name='Starttermin')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='Letzter Termin')),
                ('starttime', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit - Beginn')),
                ('endtime', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit - Ende')),
            ],
            options={
                'verbose_name': 'Veranstaltung',
                'verbose_name_plural': 'Veranstaltungen',
                'ordering': ['-startdate'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Bild')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
        ),
    ]
