# Generated by Django 3.1.4 on 2020-12-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201212_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/events/', verbose_name='Bild'),
        ),
    ]
