# Generated by Django 3.1.4 on 2021-06-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20201224_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bookable',
            field=models.BooleanField(default=True, verbose_name='Reservierbar'),
        ),
    ]
