# Generated by Django 3.1.4 on 2020-12-12 14:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nachname')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Geburtstag')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio')),
                ('position', models.IntegerField(default=90, help_text='An welcher Stelle wird die Person in der Teamübersicht aufgelistet? 1 = oben, 2 unter 1, 3 unter 2 usw.', verbose_name='Position')),
                ('active', models.BooleanField(default=True, help_text='Ist die Person derzeit aktives Mitglied von RW11?', verbose_name='Aktiv?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/team/', verbose_name='Bild')),
            ],
            options={
                'verbose_name': 'Teammitglied',
                'verbose_name_plural': 'Teammitglieder',
                'ordering': ['position'],
            },
        ),
    ]
